// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA2d3ca9txi86Ev7JRNto4e8RXipyPKbj0',
    appId: '1:854089786331:web:335c371446841d49e03dfe',
    messagingSenderId: '854089786331',
    projectId: 'budgetbitfitadviser',
    authDomain: 'budgetbitfitadviser.firebaseapp.com',
    storageBucket: 'budgetbitfitadviser.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDX3UNVUUnVoQwCWJ5hLnJgzVr_DXqLDKs',
    appId: '1:854089786331:android:868192e79ce09849e03dfe',
    messagingSenderId: '854089786331',
    projectId: 'budgetbitfitadviser',
    storageBucket: 'budgetbitfitadviser.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB-a7QleNIDIl46rPV_af0XN9ljcO9YK1M',
    appId: '1:854089786331:ios:48194e51b060998ce03dfe',
    messagingSenderId: '854089786331',
    projectId: 'budgetbitfitadviser',
    storageBucket: 'budgetbitfitadviser.appspot.com',
    iosBundleId: 'com.example.budgetbitefitadviser1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB-a7QleNIDIl46rPV_af0XN9ljcO9YK1M',
    appId: '1:854089786331:ios:48194e51b060998ce03dfe',
    messagingSenderId: '854089786331',
    projectId: 'budgetbitfitadviser',
    storageBucket: 'budgetbitfitadviser.appspot.com',
    iosBundleId: 'com.example.budgetbitefitadviser1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA2d3ca9txi86Ev7JRNto4e8RXipyPKbj0',
    appId: '1:854089786331:web:a0b42cf2adf66782e03dfe',
    messagingSenderId: '854089786331',
    projectId: 'budgetbitfitadviser',
    authDomain: 'budgetbitfitadviser.firebaseapp.com',
    storageBucket: 'budgetbitfitadviser.appspot.com',
  );
}
